### 상품 추가
POST http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ6ZE4yb0ZYOTFXUW9WbG14cVdwWGdBaXB1RjczQVI4MmpNSnlRQUcyRjRjPSIsImp0aSI6IlJETko4ZFJTMGJGYmFEMHJZaDNQZ3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzAxNDM5NTg5LCJleHAiOjE3MDE1MjU5ODl9.v_bNXddiNVS-Wv1Fh6-XmO15dYca8wVmrY6zAkNOgjQ

{
  "name": "nike airForce",
  "description": "상품 설명",
  "items": [
    {
      "count": 1,
      "name": "270",
      "price": 100000
    }
  ]
}

### 상품 아이템 추가
POST http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ6ZE4yb0ZYOTFXUW9WbG14cVdwWGdBaXB1RjczQVI4MmpNSnlRQUcyRjRjPSIsImp0aSI6IlJETko4ZFJTMGJGYmFEMHJZaDNQZ3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzAxNDM5NTg5LCJleHAiOjE3MDE1MjU5ODl9.v_bNXddiNVS-Wv1Fh6-XmO15dYca8wVmrY6zAkNOgjQ

{
  "productId": 6,
  "name": "290",
  "price": 100000,
  "count": 1
}

### 상품 수정
PUT http://localhost:8082/seller/product
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ6ZE4yb0ZYOTFXUW9WbG14cVdwWGdBaXB1RjczQVI4MmpNSnlRQUcyRjRjPSIsImp0aSI6IlJETko4ZFJTMGJGYmFEMHJZaDNQZ3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzAxNDM5NTg5LCJleHAiOjE3MDE1MjU5ODl9.v_bNXddiNVS-Wv1Fh6-XmO15dYca8wVmrY6zAkNOgjQ

{
  "name": "Air jordan 1",
  "description": "새로운 신발",
  "id": 1,
  "items": [
    {
      "id": 1,
      "count": 3,
      "name": "280",
      "price": 200000
    }
  ]
}

### 상품 아이템 수정
PUT http://localhost:8082/seller/product/item
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ6ZE4yb0ZYOTFXUW9WbG14cVdwWGdBaXB1RjczQVI4MmpNSnlRQUcyRjRjPSIsImp0aSI6IlJETko4ZFJTMGJGYmFEMHJZaDNQZ3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzAxNDM5NTg5LCJleHAiOjE3MDE1MjU5ODl9.v_bNXddiNVS-Wv1Fh6-XmO15dYca8wVmrY6zAkNOgjQ

{
  "id": 2,
  "count": 3,
  "name": "200",
  "price": 150000
}

### 상품 삭제
DELETE http://localhost:8082/seller/product?id=6
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ6ZE4yb0ZYOTFXUW9WbG14cVdwWGdBaXB1RjczQVI4MmpNSnlRQUcyRjRjPSIsImp0aSI6IlJETko4ZFJTMGJGYmFEMHJZaDNQZ3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzAxNDM5NTg5LCJleHAiOjE3MDE1MjU5ODl9.v_bNXddiNVS-Wv1Fh6-XmO15dYca8wVmrY6zAkNOgjQ

### 상품 아이템 삭제
DELETE http://localhost:8082/seller/product/item?id=8
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ6ZE4yb0ZYOTFXUW9WbG14cVdwWGdBaXB1RjczQVI4MmpNSnlRQUcyRjRjPSIsImp0aSI6IlJETko4ZFJTMGJGYmFEMHJZaDNQZ3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzAxNDM5NTg5LCJleHAiOjE3MDE1MjU5ODl9.v_bNXddiNVS-Wv1Fh6-XmO15dYca8wVmrY6zAkNOgjQ

### 상품 검색
GET http://localhost:8082/search/product?name=nike
Content-Type: application/json

### 상품 디테일 검색
GET http://localhost:8082/search/product/detail?productId=4
Content-Type: application/json
X-AUTH-TOKEN: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ6ZE4yb0ZYOTFXUW9WbG14cVdwWGdBaXB1RjczQVI4MmpNSnlRQUcyRjRjPSIsImp0aSI6IlJETko4ZFJTMGJGYmFEMHJZaDNQZ3c9PSIsInJvbGVzIjoiU0VMTEVSIiwiaWF0IjoxNzAxNDM5NTg5LCJleHAiOjE3MDE1MjU5ODl9.v_bNXddiNVS-Wv1Fh6-XmO15dYca8wVmrY6zAkNOgjQ

